config/routes.rb
Clockandclock::Application.routes.draw do

  devise_for :users

  scope "/admin" do
    resources :sizes
    resources :types
  end

   root :to => 'sizes#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  #attribute
  attr_accessible :product_id, :url

  #relationship
  belongs_to :product
end

app/models/information.rb
class Information < ActiveRecord::Base
  #attribute
  attr_accessible :description, :language, :material, :name, :price, :product_id, :currency

  #relationship
  belongs_to :product

  #Constant
  Information::VIETNAMESE = "vietnamese"
  Information::ENGLISH = "english"

  Information::VND = "VND"
  Information::USD = "USD"
end

app/models/product.rb
class Product < ActiveRecord::Base
  #attribute
  attr_accessible :size_id, :type_id

  #relationship
  belongs_to :type
  belongs_to :size

  has_many :informations
  has_many :images
end

app/models/size.rb
class Size < ActiveRecord::Base
  #attribute
  attr_accessible :length, :unit

  #relationship
  has_many :products
end

app/models/type.rb
class Type < ActiveRecord::Base
  #attribute
  attr_accessible :name

  #relationship
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController

  def index
    @sizes = Size.all
    respond_to do |format|
      format.html #index.html.haml
      format.json { render json: @sizes }
    end
  end

  def show
    @size = Size.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @size }
    end
  end

  def new
    @size = Size.new
    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @size }
    end
  end

  def edit
    @size = Size.find(params[:id])
  end

  def create
    @size = Size.new(params[:size])

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, notice: 'Size was successfully created.' }
        format.json { render json: @size, status: :created, location: @size }
      else
        format.html { render action: "new" }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @size = Size.find(params[:id])

    respond_to do |format|
      if @size.update_attributes(params[:size])
        format.html { redirect_to @size, notice: 'Size was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @size = Size.find(params[:id])
    @size.destroy

    respond_to do |format|
      format.html { redirect_to sizes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.haml
      format.json { render json: @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.haml
      format.json { render json: @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Clock Creativity
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body= yield

app/views/sizes/_form.html.haml
= form_for(@size) do |f|
  - if @size.errors.any?
    #error_explanation
      %h2
        = pluralize(@size.errors.count, "error")
        prohibited this size from being saved:
      %ul
        - @size.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :length
    %br/
    = f.text_field :length

  .field
    = f.label :unit
    %br/
    =f.text_field :unit

  .action= f.submit

app/views/sizes/edit.html.haml
%h1 Editing size
= render 'form'
= link_to 'Show', @size
|
= link_to 'Back', sizes_path

app/views/sizes/index.html.haml
%h1
  = current_user ? current_user.email.to_s : "nothing"
%h1 Listing sizes

%table
  %tr
    %th Length
    %th Unit
    %th
    %th
    %th

  - @sizes.each do |size|
    %tr
      %td= size.length
      %td= size.unit
      %td= link_to 'Show', size
      %td= link_to 'Edit', edit_size_path(size)
      %td= link_to 'Destroy', size, method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Size', new_size_path
%br/
= link_to 'Change Password', edit_user_password_path(current_user)
|
= link_to 'Sign Out', destroy_user_session_path(current_user), method: :delete

app/views/sizes/new.html.haml
%h1 New size

= render 'form'

= link_to 'Back', sizes_path

app/views/sizes/show.html.haml
%p#notice= notice
%p
  %b Length:
  = @size.length

%p
  %b Unit:
  = @size.unit

= link_to 'Edit', edit_size_path(@size)
|
= link_to 'Back', sizes_path

app/views/types/_form.html.haml
= form_for(@type) do |f|
  - if @type.errors.any?
    .error_explanation
      %h2
        = pluralize(@type.errors.count, "error")
        prohibited this type from being saved:
      %ul
        - @type.errors.full_messages.each do |msg|
          %li= msg

  #field
    = f.label :name
    %br/
    = f.text_field :name
  #actions
    = f.submit

app/views/types/edit.html.haml
%h1 Editing type

= render 'form'

= link_to 'Show', @type
|
= link_to 'Back', types_path

app/views/types/index.html.haml
%h1 Listing types

%table
  %tr
    %th Name
    %th
    %th
    %th

  - @types.each do |type|
    %tr
      %td= type.name
      %td= link_to 'Show', type
      %td= link_to 'Edit', edit_type_path(type)
      %td= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' }

%br/

= link_to 'New Type', new_type_path

app/views/types/new.html.haml
%h1 New type

= render 'form'

= link_to 'Back', types_path

app/views/types/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @type.name

= link_to 'Edit', edit_type_path(@type)
= link_to 'Back', types_path